import type { InformationToolName } from "./types.js";

export type InformationToolAccess = "free" | "premium" | "mixed";

export type InformationToolMetadata = {
  name: InformationToolName;
  provider: "exa" | "finnhub" | "supermemory";
  access: InformationToolAccess;
  purpose: string;
  useWhen: string;
  avoidWhen: string;
  input: string;
  returns: string;
  configuration: string;
};

export const INFORMATION_TOOL_CATALOG: readonly InformationToolMetadata[] = [
  {
    name: "exa_search",
    provider: "exa",
    access: "free",
    purpose: "Find current public web or news sources for a specific market claim, catalyst, company, person, sector, or ticker.",
    useWhen: "Use for freshness, source discovery, corroborating a concrete claim, or finding the first citations for recent public-market facts.",
    avoidWhen: "Do not use for private Kairos memory, ticker-only price data, or broad synthesis that needs multi-source reasoning; use exa_research for that.",
    input: "Plain-language query with the entity, catalyst, and time window when relevant. Example: PLTR government contract May 2026.",
    returns: "A capped list of source summaries and URLs. Treat it as lead generation; verify source quality and publication dates before drawing conclusions.",
    configuration: "Frontend can enable/disable this named tool.",
  },
  {
    name: "exa_research",
    provider: "exa",
    access: "free",
    purpose: "Run deeper public web research that synthesizes several sources into a cited answer.",
    useWhen: "Use for materiality checks, market maps, supply-chain questions, competitor comparisons, or explaining why a catalyst may matter.",
    avoidWhen: "Do not use when a focused search, specific URL read, or ticker metric is enough. It is more expensive and should not replace simple source lookup.",
    input: "Plain-language research question with desired scope. Example: How material are Oracle cloud GPU capacity deals for NVDA demand?",
    returns: "A compact synthesis plus grounding citations where available. Use it as evidence context, not as a trading decision.",
    configuration: "Frontend can enable/disable this named tool.",
  },
  {
    name: "exa_contents",
    provider: "exa",
    access: "free",
    purpose: "Read and summarize specific URLs that were supplied by the user or found by search.",
    useWhen: "Use when the exact source matters: filings, press releases, articles, blog posts, or pages whose details need citation.",
    avoidWhen: "Do not use for discovering sources or answering broad questions without URLs; use exa_search or exa_research first.",
    input: "One URL or text containing up to a few URLs. Example: https://investors.example.com/news/contract-award.",
    returns: "Extracted page text, summary, and citation metadata. Prefer the source text over headlines when facts conflict.",
    configuration: "Frontend can enable/disable this named tool.",
  },
  {
    name: "finnhub_api_request",
    provider: "finnhub",
    access: "mixed",
    purpose: "Call documented Finnhub REST endpoints that do not have a named convenience tool.",
    useWhen: "Use only when the injected Finnhub endpoint catalog contains a relevant endpoint and no named Finnhub tool covers the need.",
    avoidWhen: "Do not guess paths, call premium endpoints when premium access is disabled, or use this instead of a named convenience tool.",
    input: "JSON with method, endpoint path, and optional params/body from finnhubApiRequestEndpointCatalog. Example: {\"method\":\"GET\",\"path\":\"/stock/filings\",\"params\":{\"symbol\":\"AAPL\"}}.",
    returns: "Raw endpoint data summarized by the runtime. Interpret cautiously because endpoint shapes vary.",
    configuration:
      "Frontend can enable/disable this escape-hatch tool and configure whether premium Finnhub endpoints are available.",
  },
  {
    name: "finnhub_quote",
    provider: "finnhub",
    access: "free",
    purpose: "Fetch current quote, price change, daily range, and percent move for a ticker.",
    useWhen: "Use for immediate price-action context around a catalyst, especially to check whether news is already being reacted to.",
    avoidWhen: "Do not use for historical trend, volume analysis, or fundamental context; pair with candles, news, or financials when those are needed.",
    input: "Uppercase ticker symbol. Examples: PLTR, AAPL, NVDA.",
    returns: "Current quote fields such as current price, change, percent change, open, high, and low. Treat missing fields as data-quality signals.",
    configuration: "Frontend can enable/disable this named tool.",
  },
  {
    name: "finnhub_company_news",
    provider: "finnhub",
    access: "free",
    purpose: "Fetch recent company news for a ticker over the configured recent window.",
    useWhen: "Use for ticker-specific headline checks, catalyst recency, and corroborating whether public coverage exists.",
    avoidWhen: "Do not use for broad web discovery, filings-only checks, or source text extraction; use Exa or filings when those fit better.",
    input: "Uppercase ticker symbol. Examples: PLTR, AAPL, NVDA.",
    returns: "A capped list of headlines, summaries, sources, dates, and URLs. Check freshness and avoid treating repeated wire copies as independent evidence.",
    configuration: "Frontend can enable/disable this named tool.",
  },
  {
    name: "finnhub_stock_candles",
    provider: "finnhub",
    access: "premium",
    purpose: "Fetch recent daily OHLCV candle data for price trend, volatility, and volume context.",
    useWhen: "Use when the question asks about momentum, technical setup, recent drawdown/rally, or whether volume confirms a move.",
    avoidWhen: "Do not use for fresh news, company fundamentals, or if premium Finnhub access is disabled.",
    input: "Uppercase ticker symbol. Examples: PLTR, AAPL, NVDA.",
    returns: "Recent open/high/low/close/volume series. Use for context only; do not infer a trade by technicals alone.",
    configuration: "Available only when Finnhub premium access is enabled.",
  },
  {
    name: "finnhub_aggregate_indicator",
    provider: "finnhub",
    access: "premium",
    purpose: "Fetch Finnhub aggregate technical indicator signals for a ticker.",
    useWhen: "Use for a compact technical read when a debate or research question explicitly needs technical/momentum context.",
    avoidWhen: "Do not use for catalyst verification, source credibility, fundamentals, or if premium access is disabled.",
    input: "Uppercase ticker symbol. Examples: PLTR, AAPL, NVDA.",
    returns: "Technical signal aggregates. Treat as secondary context behind source-backed facts and market data.",
    configuration: "Available only when Finnhub premium access is enabled.",
  },
  {
    name: "finnhub_basic_financials",
    provider: "finnhub",
    access: "free",
    purpose: "Fetch core company metrics such as valuation, profitability, margins, growth, and balance-sheet ratios.",
    useWhen: "Use for materiality checks, sizing a catalyst against company scale, or comparing current valuation/fundamentals.",
    avoidWhen: "Do not use for new event discovery, intraday price action, or detailed as-reported statements.",
    input: "Uppercase ticker symbol. Examples: PLTR, AAPL, NVDA.",
    returns: "Metric snapshots. Use to frame magnitude and quality; confirm stale or missing metrics with other sources when important.",
    configuration: "Frontend can enable/disable this named tool.",
  },
  {
    name: "finnhub_company_earnings",
    provider: "finnhub",
    access: "free",
    purpose: "Fetch recent reported earnings and surprises for a ticker.",
    useWhen: "Use for earnings history, surprise context, and whether a catalyst overlaps with recent results.",
    avoidWhen: "Do not use for future EPS estimates, filings, or non-earnings catalysts.",
    input: "Uppercase ticker symbol. Examples: PLTR, AAPL, NVDA.",
    returns: "Recent EPS actuals/estimates and surprise data. Use as context, not as a direct action signal.",
    configuration: "Frontend can enable/disable this named tool.",
  },
  {
    name: "finnhub_company_eps_estimates",
    provider: "finnhub",
    access: "premium",
    purpose: "Fetch analyst EPS estimates for earnings expectation context.",
    useWhen: "Use when the question asks about upcoming earnings expectations, estimate revisions, or whether a catalyst could change consensus.",
    avoidWhen: "Do not use for reported results, general valuation, or if premium access is disabled.",
    input: "Uppercase ticker symbol. Examples: PLTR, AAPL, NVDA.",
    returns: "Quarterly EPS estimate data. Treat consensus as market-expectation context, not proof of future results.",
    configuration: "Available only when Finnhub premium access is enabled.",
  },
  {
    name: "finnhub_company_peers",
    provider: "finnhub",
    access: "free",
    purpose: "Fetch peer companies for sector, competitor, and relative-move checks.",
    useWhen: "Use to identify comparable companies, affected competitors, or sector baskets for follow-up research.",
    avoidWhen: "Do not use for detailed peer fundamentals by itself; use it to choose follow-up tools or queries.",
    input: "Uppercase ticker symbol. Examples: PLTR, AAPL, NVDA.",
    returns: "Ticker symbols for peers. Validate relevance before assuming direct comparability.",
    configuration: "Frontend can enable/disable this named tool.",
  },
  {
    name: "finnhub_company_profile",
    provider: "finnhub",
    access: "free",
    purpose: "Fetch company identity, industry, exchange, market cap, and profile metadata.",
    useWhen: "Use when the agent needs to confirm what company a ticker refers to, its industry, or basic scale.",
    avoidWhen: "Do not use for catalyst verification, current price, financial statements, or news.",
    input: "Uppercase ticker symbol. Examples: PLTR, AAPL, NVDA.",
    returns: "Company metadata. Use it to avoid entity confusion and frame sector/scale.",
    configuration: "Frontend can enable/disable this named tool.",
  },
  {
    name: "finnhub_earnings_calendar",
    provider: "finnhub",
    access: "free",
    purpose: "Fetch earnings calendar timing for catalyst-window awareness.",
    useWhen: "Use to check whether an upcoming or recent earnings date could explain price action or constrain a trade/research horizon.",
    avoidWhen: "Do not use for earnings results, EPS surprises, or non-earnings event calendars.",
    input: "Uppercase ticker symbol or calendar query. Example: NVDA.",
    returns: "Upcoming/recent earnings calendar records. Treat dates as scheduling context that may need company-site confirmation.",
    configuration: "Frontend can enable/disable this named tool.",
  },
  {
    name: "finnhub_filings",
    provider: "finnhub",
    access: "free",
    purpose: "Fetch recent SEC filings for a ticker.",
    useWhen: "Use for material corporate events, 8-K checks, risk disclosures, contracts, leadership changes, acquisitions, and official filing evidence.",
    avoidWhen: "Do not use for routine price/volume analysis, generic news, or if a specific URL should be read directly.",
    input: "Uppercase ticker symbol. Examples: PLTR, AAPL, NVDA.",
    returns: "Recent filing records and URLs when available. Prefer filing evidence over secondary coverage for official facts.",
    configuration: "Frontend can enable/disable this named tool.",
  },
  {
    name: "finnhub_financials_reported",
    provider: "finnhub",
    access: "free",
    purpose: "Fetch reported financial statements in as-reported form.",
    useWhen: "Use when a question needs line-item statements, reported revenue/profit/cash-flow details, or fiscal-period context.",
    avoidWhen: "Do not use for quick valuation ratios or current price; use basic financials or quote instead.",
    input: "Uppercase ticker symbol. Examples: PLTR, AAPL, NVDA.",
    returns: "As-reported financial statement data. Summarize only decision-relevant fields to avoid noisy context.",
    configuration: "Frontend can enable/disable this named tool.",
  },
  {
    name: "finnhub_insider_transactions",
    provider: "finnhub",
    access: "free",
    purpose: "Fetch recent insider transaction records for a ticker.",
    useWhen: "Use when insider buying/selling could affect confidence, explain market attention, or test governance concerns.",
    avoidWhen: "Do not use for institutional ownership, executive biographies, or routine catalyst verification.",
    input: "Uppercase ticker symbol. Examples: PLTR, AAPL, NVDA.",
    returns: "Recent insider transaction records. Interpret planned sales, grants, and small transactions cautiously.",
    configuration: "Frontend can enable/disable this named tool.",
  },
  {
    name: "finnhub_news_sentiment",
    provider: "finnhub",
    access: "premium",
    purpose: "Fetch Finnhub news sentiment signals for a ticker.",
    useWhen: "Use when the research question specifically asks about sentiment or when headline tone may help explain price action.",
    avoidWhen: "Do not use as a substitute for reading source articles, and do not use if premium access is disabled.",
    input: "Uppercase ticker symbol. Examples: PLTR, AAPL, NVDA.",
    returns: "Aggregated sentiment metrics. Treat as weak supporting context behind source-backed evidence.",
    configuration: "Available only when Finnhub premium access is enabled.",
  },
  {
    name: "finnhub_ownership",
    provider: "finnhub",
    access: "premium",
    purpose: "Fetch institutional ownership data for a ticker.",
    useWhen: "Use for holder-base questions, crowdedness, institutional sponsorship, or ownership-change context.",
    avoidWhen: "Do not use for insider transactions, current price, or if premium access is disabled.",
    input: "Uppercase ticker symbol. Examples: PLTR, AAPL, NVDA.",
    returns: "Institutional ownership records. Use for background and confirm dates before treating changes as current.",
    configuration: "Available only when Finnhub premium access is enabled.",
  },
  {
    name: "finnhub_press_releases",
    provider: "finnhub",
    access: "premium",
    purpose: "Fetch company press releases for official source checks.",
    useWhen: "Use to verify company-announced contracts, partnerships, product launches, guidance, or management statements.",
    avoidWhen: "Do not use for independent corroboration, market reaction, or if premium access is disabled.",
    input: "Uppercase ticker symbol. Examples: PLTR, AAPL, NVDA.",
    returns: "Recent press release records and URLs. Treat official claims as primary but potentially promotional.",
    configuration: "Available only when Finnhub premium access is enabled.",
  },
  {
    name: "finnhub_recommendation_trends",
    provider: "finnhub",
    access: "free",
    purpose: "Fetch analyst recommendation trend history for a ticker.",
    useWhen: "Use to understand broad analyst stance, rating distribution, or whether sell-side tone is changing.",
    avoidWhen: "Do not use for specific upgrade/downgrade events, price targets, or source verification.",
    input: "Uppercase ticker symbol. Examples: PLTR, AAPL, NVDA.",
    returns: "Recommendation counts by period. Use as slow-moving sentiment context.",
    configuration: "Frontend can enable/disable this named tool.",
  },
  {
    name: "finnhub_social_sentiment",
    provider: "finnhub",
    access: "premium",
    purpose: "Fetch social sentiment metrics for retail/social attention checks.",
    useWhen: "Use when retail attention, social momentum, Reddit/Twitter discussion, or meme-stock dynamics are directly relevant.",
    avoidWhen: "Do not use for source-backed fact verification, institutional sentiment, or if premium access is disabled.",
    input: "Uppercase ticker symbol. Examples: PLTR, AAPL, NVDA.",
    returns: "Aggregated social sentiment/attention metrics. Treat as noisy secondary evidence.",
    configuration: "Available only when Finnhub premium access is enabled.",
  },
  {
    name: "finnhub_supply_chain_relationships",
    provider: "finnhub",
    access: "premium",
    purpose: "Fetch supplier/customer relationship data for supply-chain exposure analysis.",
    useWhen: "Use for supplier/customer exposure, second-order beneficiaries, or competitor ecosystem questions.",
    avoidWhen: "Do not use for generic peer lists, company profile, or if premium access is disabled.",
    input: "Uppercase ticker symbol. Examples: AAPL, NVDA, TSM.",
    returns: "Relationship records that may be stale or incomplete. Confirm material relationships with public sources before relying on them.",
    configuration: "Available only when Finnhub premium access is enabled.",
  },
  {
    name: "finnhub_upgrade_downgrade",
    provider: "finnhub",
    access: "premium",
    purpose: "Fetch recent analyst upgrades and downgrades.",
    useWhen: "Use when analyst actions may be the catalyst, may explain price action, or may confirm changing consensus.",
    avoidWhen: "Do not use for broad recommendation distribution or if premium access is disabled.",
    input: "Uppercase ticker symbol. Examples: PLTR, AAPL, NVDA.",
    returns: "Recent upgrade/downgrade records. Check dates and firms; do not treat all analyst actions as equal quality.",
    configuration: "Available only when Finnhub premium access is enabled.",
  },
  {
    name: "supermemory_search",
    provider: "supermemory",
    access: "free",
    purpose: "Search Kairos memory for prior decisions, human corrections, preferences, branch context, and false-positive history.",
    useWhen: "Use when prior Kairos context could affect interpretation: repeated catalysts, user preferences, remembered thesis details, or duplicate suppression.",
    avoidWhen: "Do not use for fresh public facts or citations. Corroborate public claims with Exa or provider data.",
    input: "Plain-language memory query with entity, branch/law, and catalyst terms. Example: PLTR government contract false positives.",
    returns: "Relevant memory snippets with similarity metadata. Treat memory as user/context evidence, not public-source proof.",
    configuration: "Frontend can enable/disable this named tool.",
  },
] as const;

export function informationToolCatalogForAccess(input: {
  finnhubPremiumAccess?: boolean;
  availableTools?: readonly InformationToolName[];
} = {}): InformationToolMetadata[] {
  const available = new Set(input.availableTools);

  return INFORMATION_TOOL_CATALOG.filter((tool) => {
    if (available.size > 0 && !available.has(tool.name)) {
      return false;
    }

    return input.finnhubPremiumAccess || tool.access !== "premium";
  });
}
